version: '3.8'
services:
  oracle-db:
    image: gvenzl/oracle-xe
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=db-password123
    volumes:
      - oracle-data:/opt/oracle/oradata 
volumes:
  oracle-data: